echo "We are trying this practical from linux EC2"
echo "We are from TDI and learning git/gihub"
echo "I am from Pune"
echo "We are form TDI-devops_Sep-Batch"
echo "we are adding data in branch-2"
echo "I am adding this line in branch-1"
