echo "We are trying this practical from linux EC2"
echo "We are from TDI and learning git/gihub"
echo "TechData"-"sajan" 
echo "We are form TDI-devosp-Batch"
echo "hello Good evining" 
echo " Welcome to AWS account"
echo " i am from BSL"